2022-01-11 13:29:34,754 INFO     Started server process [7616]
2022-01-11 13:29:34,755 INFO     Waiting for application startup.
2022-01-11 13:29:34,757 INFO     Application startup complete.
2022-01-11 13:30:40,822 INFO     Opened landing page
2022-01-11 13:31:01,100 INFO     Shutting down
2022-01-11 13:31:01,204 INFO     Waiting for application shutdown.
2022-01-11 13:31:01,204 INFO     Application shutdown complete.
2022-01-11 13:31:01,204 INFO     Finished server process [7616]
2022-01-11 14:01:40,949 INFO     Started server process [15124]
2022-01-11 14:01:40,949 INFO     Waiting for application startup.
2022-01-11 14:01:40,955 INFO     Application startup complete.
2022-01-11 14:01:47,624 INFO     Opened landing page
2022-01-11 14:01:57,107 INFO     Opened weight page
2022-01-11 14:01:57,107 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 743, in run
    result = func(*args)
  File ".\app\main.py", line 30, in weight_plot
    result = get_weight_data()
  File ".\app\util_files.py", line 9, in get_weight_data
    df = pd.read_excel(DATA_FOLDER / "weight_data.ods")
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_odfreader.py", line 34, in __init__
    import_optional_dependency("odf")
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'odfpy'.  Use pip or conda to install odfpy.
2022-01-11 14:02:04,453 INFO     Opened weight page
2022-01-11 14:02:04,457 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 743, in run
    result = func(*args)
  File ".\app\main.py", line 30, in weight_plot
    result = get_weight_data()
  File ".\app\util_files.py", line 9, in get_weight_data
    df = pd.read_excel(DATA_FOLDER / "weight_data.ods")
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_odfreader.py", line 34, in __init__
    import_optional_dependency("odf")
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'odfpy'.  Use pip or conda to install odfpy.
2022-01-11 14:02:23,062 INFO     Started server process [17828]
2022-01-11 14:02:23,062 INFO     Waiting for application startup.
2022-01-11 14:02:23,064 INFO     Application startup complete.
2022-01-11 14:02:34,230 INFO     Started server process [9476]
2022-01-11 14:02:34,230 INFO     Waiting for application startup.
2022-01-11 14:02:34,230 INFO     Application startup complete.
2022-01-11 14:02:37,707 INFO     Opened weight page
2022-01-11 14:02:37,707 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 743, in run
    result = func(*args)
  File ".\app\main.py", line 37, in weight_plot
    result = get_weight_data()
  File ".\app\util_files.py", line 9, in get_weight_data
    df = pd.read_excel(DATA_FOLDER / "weight_data.ods")
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_base.py", line 1233, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\io\excel\_odfreader.py", line 34, in __init__
    import_optional_dependency("odf")
  File "C:\Users\PatCa\anaconda3\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'odfpy'.  Use pip or conda to install odfpy.
2022-01-11 14:02:49,590 INFO     Shutting down
2022-01-11 14:03:15,352 INFO     Started server process [16676]
2022-01-11 14:03:15,352 INFO     Waiting for application startup.
2022-01-11 14:03:15,352 INFO     Application startup complete.
2022-01-11 14:03:21,693 INFO     Opened weight page
2022-01-11 14:04:15,465 INFO     Started server process [19552]
2022-01-11 14:04:15,465 INFO     Waiting for application startup.
2022-01-11 14:04:15,465 INFO     Application startup complete.
2022-01-11 14:04:19,172 INFO     Opened weight page
2022-01-11 14:04:57,456 INFO     Started server process [19676]
2022-01-11 14:04:57,457 INFO     Waiting for application startup.
2022-01-11 14:04:57,458 INFO     Application startup complete.
2022-01-11 14:05:10,456 INFO     Started server process [20404]
2022-01-11 14:05:10,457 INFO     Waiting for application startup.
2022-01-11 14:05:10,458 INFO     Application startup complete.
2022-01-11 14:05:28,203 INFO     Started server process [18420]
2022-01-11 14:05:28,207 INFO     Waiting for application startup.
2022-01-11 14:05:28,208 INFO     Application startup complete.
2022-01-11 14:06:07,996 INFO     Opened weight page
2022-01-11 14:06:08,038 ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\PatCa\anaconda3\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "C:\Users\PatCa\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 743, in run
    result = func(*args)
  File ".\app\main.py", line 38, in weight_plot
    result = get_weight_data()
  File ".\app\util_files.py", line 11, in get_weight_data
    result = json.dumps(df)
  File "C:\Users\PatCa\anaconda3\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\PatCa\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\PatCa\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\PatCa\anaconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
2022-01-11 14:07:27,143 INFO     Started server process [11408]
2022-01-11 14:07:27,144 INFO     Waiting for application startup.
2022-01-11 14:07:27,146 INFO     Application startup complete.
2022-01-11 14:07:32,669 INFO     Opened weight page
2022-01-11 14:07:46,275 INFO     Started server process [19416]
2022-01-11 14:07:46,275 INFO     Waiting for application startup.
2022-01-11 14:07:46,275 INFO     Application startup complete.
2022-01-11 14:07:51,554 INFO     Started server process [17456]
2022-01-11 14:07:51,554 INFO     Waiting for application startup.
2022-01-11 14:07:51,554 INFO     Application startup complete.
2022-01-11 14:07:54,311 INFO     Opened weight page
2022-01-11 14:08:11,882 INFO     Started server process [16568]
2022-01-11 14:08:11,883 INFO     Waiting for application startup.
2022-01-11 14:08:11,884 INFO     Application startup complete.
2022-01-11 14:08:42,906 INFO     Started server process [10436]
2022-01-11 14:08:42,907 INFO     Waiting for application startup.
2022-01-11 14:08:42,908 INFO     Application startup complete.
2022-01-11 14:08:53,415 INFO     Started server process [18360]
2022-01-11 14:08:53,416 INFO     Waiting for application startup.
2022-01-11 14:08:53,417 INFO     Application startup complete.
2022-01-11 14:08:55,588 INFO     Opened weight page
2022-01-11 14:11:55,700 INFO     Started server process [10596]
2022-01-11 14:11:55,701 INFO     Waiting for application startup.
2022-01-11 14:11:55,702 INFO     Application startup complete.
2022-01-11 14:12:16,452 INFO     Started server process [17900]
2022-01-11 14:12:16,458 INFO     Waiting for application startup.
2022-01-11 14:12:16,458 INFO     Application startup complete.
2022-01-11 14:12:21,851 INFO     Opened weight page
2022-01-11 14:13:22,464 INFO     Started server process [18272]
2022-01-11 14:13:22,464 INFO     Waiting for application startup.
2022-01-11 14:13:22,469 INFO     Application startup complete.
2022-01-11 14:15:13,696 INFO     Shutting down
2022-01-11 14:15:13,811 INFO     Waiting for application shutdown.
2022-01-11 14:15:13,811 INFO     Application shutdown complete.
2022-01-11 14:15:13,811 INFO     Finished server process [18272]
